#!/usr/bin/php
<?php
set_include_path(get_include_path() . PATH_SEPARATOR . realpath(dirname(__FILE__)));

require 'lib/Zend/Exception.php';
require 'lib/Zend/Config.php';
require 'lib/Zend/Config/Exception.php';
require 'lib/Zend/Config/Ini.php';

if (file_exists(__DIR__ . '/../../autoload.php')) {
    // jumpstorm is part of a composer installation
    include __DIR__ . '/../../autoload.php';
} else {
    include_once __DIR__.'/lib/Symfony/Component/ClassLoader/UniversalClassLoader.php';
}

use Symfony\Component\ClassLoader\UniversalClassLoader;

$loader = new UniversalClassLoader();

// load default namespaces
$namespaces = array(
    'Jumpstorm'        => __DIR__.'/src',
    'Netresearch'      => __DIR__.'/lib',
    'Symfony'          => __DIR__.'/lib',
    'Zend'             => __DIR__.'/lib'
);

// add plugin namespaces dynamically
$pluginDirs = glob(__DIR__.'/plugins/*', GLOB_ONLYDIR);
foreach ($pluginDirs as $path) {
    $namespaces[basename($path)] = dirname($path);
}

$loader->registerNamespaces($namespaces);
$loader->registerNamespaceFallbacks(array(__DIR__.'/src'));
$loader->register();

use Symfony\Component\Console\Application;

$console = new Application('Jumpstorm', '0.1');
$console->add(new Jumpstorm\Magento());
$console->add(new Jumpstorm\Unittesting());
$console->add(new Jumpstorm\Extensions());
$console->add(new Jumpstorm\Plugins());
$console->run();
