; Sample configuration file for jumpstorm

# some settings to be asked if not set
ask:
    - "common.magento.target"
    - "common.db.name"

# some settings to be explicitly confirmed by the user
confirm:
    - "common.magento.target"
    - "common.db.name"

common:
    magento:
        target: "/home/user/public/htdocs"

    db:
        name:   magento
        host:   localhost
        user:   root
        pass:   <your_database_password>
        prefix: ~

magento:
    source:         git://github.com/LokeyCoding/magento-mirror.git
    branch:         magento-1.7.0.2
    baseUrl:        mymachine.local
    adminFirstname: Firstname
    adminLastname:  Lastname
    adminEmail:     firstname.lastname@example.org
    adminUser:      admin
    adminPass:      admin123

    sampledata:
        source: git://github.com/openstream/magento-sample-data.git
        branch: master

unittesting:
    framework:  ecomdev
    extension:
        source: git://github.com/IvanChepurnyi/EcomDev_PHPUnit.git
        branch: master

extensions:
#    my_ext:
#        source: git@git.example.org:extensions/my_ext.git
#        branch: master #optional

#    fooman_speedster:  magentoconnect://community/Fooman_Speedster

    germansetup:       git://github.com/firegento/firegento-germansetup.git
    locale_de:         git://github.com/riconeitzel/German_LocalePack_de_DE.git

    # simple product import, required by plugin DummyProducts
    #FastSimpleImport: git://github.com/avstudnitz/AvS_FastSimpleImport.git

plugins:
# settings needed by the plugins to be executed
    DisableAdminNotifications:
        enabled: 0

    #CreateBackendUser:
        #ini: plugins/CreateBackendUser/CreateBackendUser.sample.ini

    ApplyConfigSettings:
        design/head/demonotice: 1

    InitGermanSetup: 1

    # add 15 sample products
    # requires sample data
    # requires AvS_FastSimpleImport
    #DummyProducts:
    #   simpleProducts: 15

    Reindex:
        #- catalog_product_attribute
        - catalog_product_price
        - catalog_url
        #- catalog_product_flat
        #- catalog_category_flat
        #- catalog_category_product
        #- catalogsearch_fulltext
        - cataloginventory_stock
        #- tag_summary

    FlushCache: 1
